### ISSUE TITLE
5.0版本SDK需要proxy来连接，现在的启动脚本中没有proxy

### ISSUE THREAD

**Issue by yimik** [Xuchengen/rocketmq-docker-build#1]

**Comment by hf-hf** [comment]
临时方案在宿主机把容器MergedDir目录下的/home/app/.run.sh追加上了--enable-proxy，只要不移除容器，启动重启都行，5.0 sdk试了一下连8081正常。

**Comment by yimik** [comment]
> 临时方案在宿主机把容器MergedDir目录下的/home/app/.run.sh追加上了--enable-proxy，只要不移除容器，启动重启都行，5.0 sdk试了一下连8081正常。

目前我也是这么解决的🤣

**Comment by tudan110** [comment]
> 临时方案在宿主机把容器MergedDir目录下的/home/app/.run.sh追加上了--enable-proxy，只要不移除容器，启动重启都行，5.0 sdk试了一下连8081正常。

具体该怎么操作呢，我在 docker desktop 里面

**Comment by yimik** [comment]
> > 临时方案在宿主机把容器MergedDir目录下的/home/app/.run.sh追加上了--enable-proxy，只要不移除容器，启动重启都行，5.0 sdk试了一下连8081正常。
> 
> 具体该怎么操作呢，我在 docker desktop 里面

可以在docker desktop容器的Terminal里执行相关命令或修改相关文件
![image](https://user-images.githubusercontent.com/7576454/206975598-6216a176-9e87-4918-97b5-8a520264ee50.png)

**Comment by tudan110** [comment]
> > > 临时方案在宿主机把容器MergedDir目录下的/home/app/.run.sh追加上了--enable-proxy，只要不移除容器，启动重启都行，5.0 sdk试了一下连8081正常。
> > 
> > 
> > 具体该怎么操作呢，我在 docker desktop 里面
> 
> 可以在docker desktop容器的Terminal里执行相关命令或修改相关文件 ![image](https://user-images.githubusercontent.com/7576454/206975598-6216a176-9e87-4918-97b5-8a520264ee50.png)

赞，谢谢
